config/routes.rb
Ath::Application.routes.draw do
  resources :users
  root to: "user#create"
  resources :sessions
  root to: "session#create"

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	attr_accessible :email, :password, :password_confirmation

	validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

	def current_user
		@corrent_user ||= User.find(session[:user_id]) if session[:user_id]
	end

helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged In!"
  	else
  		flash.now.alert = "Email or password is invalid!"
  		render "new"
  	end
  end

  def destroy 
  	session[:user_id] = nil
  	redirect_to root_url, norice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new 
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_url, notice: "Thank you for sign up!"
		else
			render "new"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>Authentication</title>
  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="container">
			<div id="user_header">
			<% if current_user %>
				Logged in as <%= current_user.email %>.
				<%= link_to "Log Out!", session_path("current") %>
			<% else %>
				<%= link_to "Sign Up", new_user_path %> or
				<%= link_to "Sign In", new_session_path %>
			<% end %>
			</div>

			<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, id: "flash_#{name}" %>
			<% end %>

			<%= yield %>
		</div>
	</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class = "error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li> <%= message %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class = "field">
		<%= f.label :email %> <br />
		<%= f.text_field :email %>
	</div>
	<div class = "field">
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
	</div><div class = "field">
		<%= f.label :password_confirmation %> <br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions"><%= f.submit %> </div>
<% end %>